### ISSUE TITLE
Using Twilio 3.x on iOS 11.0+ on project having deployment target as 10.0

### ISSUE THREAD

**Issue by ajeetpratap** [twilio/twilio-video-ios#101]
### Description
Hi, My project has deployment target of 10.0. I am want to use Twilio3.x SDK for my user who are on iOS 11 and above. So there won't be any support for iOS 10 users. 
I added the SDK and it builds and run fine on device but when I try to archive it, it gives me error saying armv7 architecture not found.
I tried marking Twilio SDK as optional in Build phases setting but still getting the same error.
Is it possible to ship the latest Twilio SDK on deployment target as 10.0 but make it only available for user above 11.0

**Comment by paynerc** [comment]
@ajeetpratap,

TwilioVideo supports iOS 11 and greater. Apple removed 32-bit support starting with iOS 11, and as such we no longer provide the 32-bit armv7 slice. The linker is failing on the 32-bit slice because there is no 32-bit slice of the framework.

I am not sure how to satisfy the linker to make a 32 bit version of your application while also attempting to include Twilio Video which only supports 64-bit platforms. One thing to try may be the wrapping of all Twilio Video calls with the `@available` blocks as such:

```
if (@available(iOS 11.0, *)) {
   ...
}
```

But I am not 100% positive that this approach is going to solve your 32-bit linking errors.

Ryan

**Comment by ajeetpratap** [comment]
Tried using @available block, still same error. For now I have switched to the older SDK and its compiling fine.
