### ISSUE TITLE
screen sharing via broadcast extension iOS 

### ISSUE THREAD

**Issue by dsngeu** [twilio/twilio-video-ios#102]
In our iOS application we have capability to broadcast screen content out side the app. so we are using Replay kit for that.

Can I use same twilio token for parent app(peer to peer connection) and for the broad cast extension(screen sharing)? 

in the current situation If I try to connect **broadcast extension** with same token(same token used in parent app)  then i get the error in broadcast token "Participant disconnected because of duplicate identity"

**Comment by dsngeu** [comment]
@Gipetto @paynerc

**Comment by piyushtank** [comment]
@dsngeu From app, you will have to connect to the Room as a separate participant than the one from the broadcast extensions. On app side, you should have logic to recognize that the video feed you are receiving from the broadcast extension running on the same phone so that it doesn't show the UI of a separate participant. Similarly you should use `isAutomaticSubscriptionEnabled` [[example](https://github.com/twilio/video-quickstart-ios/blob/b74e1c1c4f49ae23f326bd3e53ec750f126d5b2d/ReplayKitExample/BroadcastExtension/SampleHandler.swift#L82)] on your broadcast extension side.

Unfortunately I don't have a better solution than proposing a work around at this time. We plan to investigate and update our app in future on how to pass information (possibly video frames) to/from app to extension.

Let me know if you have any questions.

**Comment by dsngeu** [comment]
@piyushtank thank you for your reply, it helps me alot
