### ISSUE TITLE
Unable to export IPA file

### ISSUE THREAD

**Issue by Suresht-0821** [twilio/twilio-video-ios#115]
Hi,
 I got the below error, when trying to export iPA file.

Failed to verify bitcode in TwilioVideo.framework/TwilioVideo:
error: Linker option verification failed for bundle /var/folders/l4/0x_14ww957j3_1l9k_jj48p40000gn/T/TwilioVideoyxBa8l/TwilioVideo.arm64.xar (unrecognized arguments: -platform_version iOS 11.0 13.4)

Please help on this issue.

Thanks,
Suresh T.

**Comment by paynerc** [comment]
@Suresht-0821,

What version of Xcode are you building your application with and trying to export the IPA from?

Ryan

**Comment by Suresht-0821** [comment]
Xcode 10.x

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by paynerc** [comment]
@Suresht-0821,

Take a look at the [Supported Xcode versions and Bitcode](https://www.twilio.com/docs/video/ios-getting-started#supported-xcode-versions-and-bitcode) section in the [iOS Getting Started Guide](https://www.twilio.com/docs/video/ios-getting-started).

The `3.x` versions of `TwilioVideo.framework` are built with Xcode 11. The framework can be consumed with previous versions of Xcode. However, re-compiling Bitcode when exporting for Ad Hoc or Enterprise distribution requires the use of Xcode 11.x. 

Per a discussion with Apple:

> Bitcode is designed to be backward compatible but not forward compatible, which means bitcode frameworks built with older Xcode can be used by newer Xcode but not the other way around. 

I hope this helps.

Ryan

**Comment by Suresht-0821** [comment]
Thanks. I got it.

I installed sample application VideoQuickstart in my device.

I just open app. Its asking Room.

what is Room ?. 

How i can create room and where ?. How two devices connect ?

Please help me on this.

Thanks in advance.

**Comment by paynerc** [comment]
@Suresht-0821,

Please take a look at the [`README.md`](https://github.com/twilio/video-quickstart-ios/blob/master/README.md) file for the Quickstart applications. It guides you through obtaining access tokens and what is needed to get two devices connected in a room.

For further information about the Twilio Video iOS SDK, please see the [Getting Started](https://www.twilio.com/docs/video/ios-getting-started) guide which covers the concepts used in the SDK.

Since you are now able to export IPA's containing the `TwilioVideo.framework` I am going to close this issue. If you have further issues related to the Quickstart applications, please file an issue in the [Quickstart repo](https://github.com/twilio/video-quickstart-ios/issues).

Ryan
