### ISSUE TITLE
Can I get the underlying AVCaptureSession and CMSampleBufferRef for processing further

### ISSUE THREAD

**Issue by mihir-mehta** [twilio/twilio-video-ios#134]
Is it possible to get the frames from the Camera feed while Video streaming is happening through Twilio SDK. 

I want to pass the camera feed (Local camera) to ML model while it's being transmitted to live streaming through twilio webRTC GO. 

Is it possible to do that ? 

Thanks

**Comment by azei** [comment]
This is something I'm also very interested in (but for audio & video recording purposes).

**Comment by ceaglest** [comment]
Hey @mihir-mehta,

> Is it possible to get the frames from the Camera feed while Video streaming is happening through Twilio SDK.

At the moment the only way to accomplish this is to operate an `AVCaptureSession` yourself and implement a `TVIVideoSource`. Then you can pre-process the frames using an ML model before delivering them to Twilio.

- [Video Source Guide (see example links)](https://www.twilio.com/docs/video/ios-v3-video-source-apis)

Hi @azei,

> This is something I'm also very interested in (but for audio & video recording purposes).

If you want to record but not modify the local media then you could accomplish this with TVIAudioSink and TVIVideoRenderer. We don't use AVCaptureSession for audio since it isn't suitable for real-time recording with playback.

For audio recording we have [AudioSinkExample](https://github.com/twilio/video-quickstart-ios/tree/master/AudioSinkExample). For video recording there is a good discussion in https://github.com/twilio/video-quickstart-ios/issues/225.

Best,
Chris

**Comment by azei** [comment]
Thank you for the info and clarification @ceaglest!

My comment is related to issue #141, more specifically if there is a way to get audio samples from Twilio without a PeerConnection established:

`Known Issues: Local audio samples are not raised until at least one underlying WebRTC PeerConnection is negotiated`

For our use case, we need to record the audio before and after a participant connects to the session, and we also can't have the recording be interrupted in the case of a lost network connection. Furthermore, we use a mix of group and peer-to-peer rooms so establishing a PeerConnection can sometimes not be done until another participant joins.

Is there any documentation of how the audio processing is done internally so we can better understand how we can achieve this?

**Comment by mihir-mehta** [comment]
Thank you @ceaglest ... Infact i am processing the camera feed and passing it to TVIVideoSource currently.... Something on the same line. Thank you for validating that solution. Do i need to tweak any default config or setting if i go with the approach.
