### ISSUE TITLE
iOS arm64 Simulator Support

### ISSUE THREAD

**Issue by paynerc** [twilio/twilio-video-ios#144]
Ahoy!

With Apple’s release of the M1 processor Macs, the Xcode iOS simulator running on these Macs use binaries compiled for the Mac `arm64` architecture. Currently the Twilio Video iOS SDK does not contain a slice that supports that `arm64` simulator on these new M1 based systems.

We are currently working on supporting the `arm64` simulator first in our internal dependencies and carrying that forward into the Twilio Video iOS `4.x` SDK.

**Comment by jigar007** [comment]
+1

**Comment by ptsochantaris** [comment]
Thank you for being aware and tracking this issue. As you can probably understand it's getting to be a bit of a blocker, do you have a timeline for when this issue might be fixed?

**Comment by hardikdevios** [comment]
Any workaround to run on the simulator with cocoa pods ?

**Comment by paynerc** [comment]
@hardikdevios

We are working towards a release that will bring `arm64` simulator support. I can't state a timeframe for this release, but we are actively working on this at this moment. As soon as I know more about a date, I will update this issue.

Ryan

**Comment by janremes** [comment]
@paynerc 

Hi, just checking in, it's two months since the last update. Is there any progress or time estimate?
It's also a bit blocker for our team. Since more and more people are using M1 macs.
Thanks for update!

**Comment by mrkvans** [comment]
@paynerc While support for Simulator on the Apple Silicon M1 macs is pending, does the  Twilio Video iOS 4.x SDK work with an attached iPhone? I'm having trouble compiling the code on the M1 period - Which means I haven't been able to use my MacBook for development on Twilio Projects since we added it as a dependency 2 mo ago...

Any updates on timing/progress are greatly appreciated.

**Comment by ptsochantaris** [comment]
@mrkvans For what it's worth, we are able to compile fine on M1 Macs for devices, and also for running as a Mac app (i.e. without the Sim) - so if you are having issues there it may be a configuration issue worth investigating.

That said, there's no substitute for debugging apps in the Sim, and in a month it's going to be a year since Apple released Xcode betas with support for ARM Sim slices in frameworks, plus close to half a year since M1 Macs started shipping. It's quite frustrating that Twilio seems to consider this a matter of such low priority, and quite in contrast to every other SDK used in our projects. Nobody expected next-day readiness, but we're almost at the next WWDC at this point. I really hope this issue gets addressed soon.

**Comment by paynerc** [comment]
@mrkvans,

I am very sorry to have not gotten back to you. I did have a response typed but I guess I didn't actually post it 😞. The answer is yes, you can definitely build and debug on device using an M1 Mac. I do have an M1 Mac here for development and testing and this definitely works.

@ptsochantaris,

Yes, I totally understand the frustration regarding not being able to run on the simulator on the M1 Macs. The short story is that we have a lot of other dependencies inside the SDK that require updating to support the `arm64` simulator slice. During that work, other changes were pulled in along the way, and we are still working to resolve those changes and get the release out. I have raised the importance of this issue to the necessary folks and I am trying to get a timeframe when this will support will become available. I am really hopeful that we will be able to get this out to you guys soon.

Thank you for your continued patience,

Ryan

**Comment by mrkvans** [comment]
@paynerc 
Do you have any new information about support for ARM64? 

Based on Apple's last earnings call (April 28), M1-based Macs are the "majority of Mac sales." 

Thanks for any additional information or timelines you're able to provide. 
Mark

**Comment by paynerc** [comment]
@mrkvans,

Unfortunately I do not have much further information regarding this. Our team is actively working on this endeavor. Internally we also require this work to be completed as these updated dependencies are critical to further feature development. I know this isn't an answer that anybody wants to hear but the best I can offer at this time is the right people are aware of the critical nature of this issue and it is actively being addressed. When we have an artifact that we can release I will update this issue with that information.

Again, thank you for your continued patience,

Ryan

**Comment by emreond** [comment]
Hello,

Our projects also rely on this SDK and we are unable to run the project natively (without Rosetta etc..) on Simulator right now. Any update will be appreciated. Thank you.

By the way; You can run it on Xcode 12.2 with Rosetta. I know this is not best approach but what we have right now. 
P.S: Remove all derived data before doing this.

**Comment by trustfall** [comment]
This is also an issue for our team as well as we have multiple people on M1.

**Comment by kyledotmp3** [comment]
This is a large issue for our team and our CI pipeline that includes UITesting

**Comment by ptsochantaris** [comment]
To add to the existing issues mentioned above, this is additionally hindering our adoption of SwiftUI; given that SwiftUI previews build as Sim binaries, which fails if we include an SDK which doesn't support that target on new Macs.

**Comment by Ashok28** [comment]
Hi,

seems crazy to me, that Apple is on its way to release a second generation of ARM computers in coming days, yet we're still yet to receive an updated version of this SDK. This has been a major pain for us in a last few months, would really love some update.

Thank you!

**Comment by paynerc** [comment]
All,

I would like to announce that we have released Twilio Video iOS `4.6.0-beta1` which includes support for running the simulator on Apple Silicon devices. The release is in beta as there are still a few known issues that we are working to resolve, but wanted to get this into your hands sooner rather than later.

Please see the [Changelog entry](https://www.twilio.com/docs/video/changelog-twilio-video-ios-latest#460-beta1-june-8-2021) for further details of the changes in the `4.6.0-beta1` release.

If you experience any issues with the SDK while running on the simulator on an M1 Mac, please open an issue here so we can track it down.

I want to personally apologize for the long delay in getting this support out to you, the Apple Developer community. Thank you for your patience and be sure to let us know if you experience any issues with this beta.

Ryan

**Comment by ceaglest** [comment]
For example apps that use the beta see: [video-quickstart-ios/tree/4.6.0-beta](https://github.com/twilio/video-quickstart-ios/tree/4.6.0-beta).

**Comment by sjmadsen** [comment]
Thank you for making this beta available.

What is the status of an official release? The `-beta1` suffix on the framework's version string blocks TestFlight submissions because it doesn't follow Apple's requirements:

`Error Domain=ITunesTransporterErrorDomain Code=-18000 "error: App Store Connect Operation Error. ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '4.6.0-beta1' in the Info.plist file at '${bundlePath}' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"."`

**Comment by ceaglest** [comment]
Hi Developers,

We have made the 4.6.0 release with arm64 simulator support available. Please have a look at:

* [SDK - v4.6.0](https://www.twilio.com/docs/video/changelog-twilio-video-ios-latest#460-september-17-2021)
* [Video App - v0.82](https://github.com/twilio/twilio-video-app-ios/releases/tag/v0.82)
* [Quickstart](https://github.com/twilio/video-quickstart-ios)

> The -beta1 suffix on the framework's version string blocks TestFlight submissions because it doesn't follow Apple's requirements:

Thank you for this feedback, we will consider it for future beta / pre-release versions. We use an enterprise account to distribute SDK betas outside of TestFlight so unfortunately we didn't run into the same challenge as you did.

Best,
Chris
