### ISSUE TITLE
dyld: Library not loaded using SwiftPM

### ISSUE THREAD

**Issue by felixliebau** [twilio/twilio-video-ios#155]
### Description

If I add the SDK to our framework (named RemoteControl) I get the following output/crash immediatly at the launch of our app which is linked to the RemoteControl framework. 

In this scenario the app has a dependency to the RemoteControl framework which has the dependency to the SDK.
I think there seems to be an issue with the code signing which I don't know how to resolve. 

I found this SwiftPM bug during my research: https://bugs.swift.org/browse/SR-13343 
Could this bug relate to my crash? 

### Steps to Reproduce

1. Create a framework
2. Add the SDK to that framework via SwiftPM 
3. Create a simple app, add the framework to the app

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

The app should launch.

#### Actual Behavior

The app crashes with the output listed in 'Logs'.

#### Reproduces How Often

100%

#### Logs

```
dyld: Library not loaded: @rpath/TwilioVideo.framework/TwilioVideo
  Referenced from: /private/var/containers/Bundle/Application/4F6D4DFA-43A7-45CF-83DB-ED68BCB69E5E/APP.app/Frameworks/RemoteControl.framework/RemoteControl
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/4F6D4DFA-43A7-45CF-83DB-ED68BCB69E5E/APP.app/Frameworks/RemoteControl.framework/Frameworks/TwilioVideo.framework/TwilioVideo: code signature in (/private/var/containers/Bundle/Application/4F6D4DFA-43A7-45CF-83DB-ED68BCB69E5E/APP.app/Frameworks/RemoteControl.framework/Frameworks/TwilioVideo.framework/TwilioVideo) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

4.0.0 and 4.0.1 via SwiftPM

#### Xcode

12.3

#### iOS Version

14.3

#### iOS Device

iPad Pro (12.9-inch) (3rd generation)

**Comment by paynerc** [comment]
@felixliebau,

You are correct that the SwiftPM bug report you referenced above is indeed the issue. We have support for this in the QuickStart applications but failed to document the requirement in our documentation. I have created tasks internally to update our documentation on the [Twilio web site](https://www.twilio.com/docs/video/ios) as well as updating the `README.md` at the root of this repository. Unfortunately that was missed during the `4.0` release.

In the meantime before I get this documentation updated, take a look at the [Video Quickstart](https://github.com/twilio/video-quickstart-ios) repo for the workaround to this SPM/Xcode issue. The key is adding a `Run Script` build phase after the `Embed Frameworks` build phase that runs the following command:

```
find "${CODESIGNING_FOLDER_PATH}" -name '*.framework' -print0 | while read -d $'\0' framework 
do 
    codesign --force --deep --sign "${EXPANDED_CODE_SIGN_IDENTITY}" --preserve-metadata=identifier,entitlements --timestamp=none "${framework}" 
done
```

As you saw from the SwiftPM bug report, this is indeed a known issue and we are hopeful that this will be fixed in a future Xcode release.

Again, I apologize for not ensuring that our documentation mentioned this issue and offered a workaround. I will be addressing that today.

Ryan

**Comment by paynerc** [comment]
@felixliebau,

I have published the documentation updates both to the `README.md` file in this repository as well as the documentation pages on the Twilio website.

Let me know if you are still experiencing issues after adding the documented workaround or if we can close this issue.

Thank you,

Ryan

**Comment by felixliebau** [comment]
@paynerc,

I have added the workaround and the app launches totally fine now. 

Thanks for your quick answer and the updated documentation, 

Felix

**Comment by jimmycooks9** [comment]
Hi @paynerc - I am running into this issue also. I'm adding TwilioVideo as a package dependency of a standalone framework. I am then importing the framework into my main app project... how can I get it to work with TwilioVideo? It is the only framework that won't work out of many...

**Comment by colincavil112** [comment]
@felixliebau - hey. how did you manage to get it to work? 

Few questions to be more clear...

**1.** Did you add `-ObjC` to Other Linker Flags in the app target's build settings, project build settings or both?
**2.** Did you add `-ObjC` to Other Linker Flags in the framework's target build settings, project build settings or both? 
**3.** Did you add the `Run Script` in build phases to the target building settings of the framework you import into the app or the actual app target's build settings? 

Thanks in advance...really struggling with this. Seems @jimmycooks9 is as well.
