### ISSUE TITLE
Get UIImage from VideoFrame 

### ISSUE THREAD

**Issue by Goule** [twilio/twilio-video-ios#185]
Hello,

I'm trying to get the video frame for some participant to re-broadcast it to another destination but I can't find how to do it. 
In fact what I need is a `CVPixelBuffer` in `kCVPixelFormatType_32ARGB` to give it to my RTMP broadcaster.

I tried to firstly get an image from the buffer to test. 
Here is the sample code to pass from buffer to CIImage (the format needed in my use case) : 
```swift 
let buffer = frame.imageBuffer // Frame is VideoFrame
let ciimage = CIImage(cvImageBuffer: buffer)
```

And here is the error : 
`[api] -[CIImage initWithCVPixelBuffer:options:] failed because its pixel format f420 is not supported.`

I found this issue https://github.com/twilio/video-quickstart-ios/issues/123, but the solution is really old and uses https://github.com/caojianhua/libyuv-iOS which is not maintained. 

Since this post, is there a more simple solution do to it? 

This is my last problem before checking if Twilio is suitable for my need! :) 

Thanks

**Comment by ceaglest** [comment]
Hi @Goule,

> I'm trying to get the video frame for some participant to re-broadcast it to another destination but I can't find how to do it.
In fact what I need is a CVPixelBuffer in kCVPixelFormatType_32ARGB to give it to my RTMP broadcaster.

I would ask your broadcaster if they could accept `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange` or `kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange` since this tends to be the preferred format for raw 8-bit SDR video on iOS. However, if you have to convert to `kCVPixelFormatType_32ARGB` then I suggest using [vImageConvert_420Yp8_Cb8_Cr8ToARGB8888](https://developer.apple.com/documentation/accelerate/1533193-vimageconvert_420yp8_cb8_cr8toar) for this task.

Best,
Chris

**Comment by Goule** [comment]
Thanks @ceaglest ! 

Have you any code sample to convert VideoFrame data with `vImageConvert_420Yp8_Cb8_Cr8ToARGB8888`? 
I tried but this is really complicated for me to manipulate this... 

Thanks

**Comment by Goule** [comment]
Another solution is to force the H264 in Twilio settings if you are using Group room : 

<img width="780" alt="Capture d’écran 2021-05-07 à 14 20 47" src="https://user-images.githubusercontent.com/21126201/117448982-b63a3300-af3f-11eb-9113-118187ac4b4b.png">

**Comment by ceaglest** [comment]
Hi @Goule,

Yes if you are okay to use H.264 for all your Participants then this solution will work. It's important to note that video from `TVICameraSource` is always `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange` if you render it locally. The remote video is from a decoder, and the H.264 decoder does decode to `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange`.

Best,
Chris

**Comment by iamraafay** [comment]
Is there a way I can programmatically set the codec in the code rather than changing it for all from the dashboard?
