### ISSUE TITLE
Best settings for quality usage 

### ISSUE THREAD

**Issue by Goule** [twilio/twilio-video-ios#196]
Hello, 

I'm working on an app that permits to broadcast of church events on socials networks from a phone. 
Twilio permit us to link multiple cameras to a production phone with different video angles. 

WebRTC seems to be designed for resilience and the received resolution from participants in a room can be really low just if the phone is moving. The quality upgrade during the stream makes a lot of time after a downgrade. 

Is there any way to parameter this behavior and make WebRTC more "aggressive" with the resolution ?

Thanks for your help

**Comment by ceaglest** [comment]
Hi @Goule,

An interesting use case.

> I'm working on an app that permits to broadcast of church events on socials networks from a phone.
Twilio permit us to link multiple cameras to a production phone with different video angles.

Yes, is there some software that allows you to control the cameras and receive frames from them?

> WebRTC seems to be designed for resilience and the received resolution from participants in a room can be really low just if the phone is moving. The quality upgrade during the stream makes a lot of time after a downgrade.

> Is there any way to parameter this behavior and make WebRTC more "aggressive" with the resolution ?

The quality based scaling can be a bit aggressive at times. For now, if you're writing your own TVIVideoSource you could mark the content as screen content by returning true from the [`screencast`](https://twilio.github.io/twilio-video-ios/docs/latest/Protocols/TVIVideoSource.html#//api/name/screencast) property. This will prioritize detail at the expense of motion and typically will not downscale the video.

If there are few publishers and many subscribers in a Group Room it would be best to use VP8 simulcast otherwise for best quality on the subscriber side.

Best,
Chris

**Comment by Goule** [comment]
Hello @ceaglest,

Thanks for your help. 

I've just tested, with `isScreencast` the resolution is great and hight, but the frame rate seems to be too lower and I can see some twitch on the screen :'( 
I guess we don't have the hand on it and this is WebRTC behavior. 

Florian
