### ISSUE TITLE
Interop issue between iOS SDK 4.6 and Chrome 94

### ISSUE THREAD

**Issue by shaibt** [twilio/twilio-video-ios#211]
### Description

Using `TwilioVideo` ver 4.6 (latest iOS version) and Chrome browser (94 on OSX) using `twilio-video-js` ver 2.13.1.
In P2P room, Chrome browser side video and audio is not received on iOS (intermittently) and logs show Client is unable to create or apply a local media description. 
Results in iOS side unable to hear/see Chrome side 

[Opened originally](https://github.com/twilio/twilio-video.js/issues/1504) in the `twilio-video-js` repo but on request of @ceaglest reopening it here.

### Steps to Reproduce

Is not consistently reproducible. Comment from original issue:

> As to reproducibility: its quite consistent for us but not 100%. We have a certain combination of devices where it happens a lot (not always) and other were it doesn't at all.

@ceaglest reported that he was able to reproduce.

#### Logs

Log of unsuccessful session on iOS side:
[twilio.log](https://github.com/twilio/twilio-video-ios/files/7309746/twilio.log)

### Devices and versions

1) Chrome 94 on OSX Big Sur 11.5.2, `twilio-video-js` ver 2.13.1
2) iPad Air 4th Gen, iOS 14.4, `TwilioVideo` ver 4.6

#### Xcode

Xcode 12.5

**Comment by ceaglest** [comment]
Hi @shaibt,

Thank you for capturing this issue. 

I was indeed able to reproduce this problem with real devices, and in unit tests with mocks of Chrome M94 SDPs. A fix to the mobile SDKs was agreed to with the team last Friday and I am working on it this week (though today is Thanksgiving holiday in Canada). Due to the nature of the bug it does need to be fixed on the mobile SDKs and can't be resolved by updating our JavaScript SDK, or our Servers.

I have tagged the fix for our 4.6.1 release as this is my best guess on where the changes will land.

Best,
Chris

**Comment by ceaglest** [comment]
Hi @shaibt,

We have just released [4.6.1](https://www.twilio.com/docs/video/changelog-twilio-video-ios-latest#461-october-15-2021) which should resolve the interoperability issue with Chrome 94. Would you mind trying it and confirming that it fixes the problem in your app?

Best,
Chris

**Comment by shaibt** [comment]
Hi @ceaglest ,

Can confirm we cannot reproduce the issue between iOS 4.6.1 and Chrome 94.
Thanks for the quick turnaround on this issue.
