### ISSUE TITLE
Audio Input issue. Input device is always bottom microphone( even if I set it to use the front one).

### ISSUE THREAD

**Issue by resetnic** [twilio/twilio-video-ios#213]
### Description

Audio Input issue. Input device is always the bottom microphone even if I set it to be the front, back, etc. 

I followed the steps from [this](https://www.twilio.com/docs/video/ios-v2-configuring-audio-video-inputs-and-outputs) tutorial.

#### Code

```swift
        let audioDevice = DefaultAudioDevice()
            TwilioVideoSDK.audioDevice = audioDevice
            audioDevice.block = { [weak self] in
                do {
                    DefaultAudioDevice.DefaultAVAudioSessionConfigurationBlock
                    
                    let audioSession = AVAudioSession.sharedInstance()
                    try audioSession.setCategory(.playAndRecord, mode: .default, options: [.defaultToSpeaker, .allowBluetooth, .allowBluetoothA2DP])

                    if let builtInMicInput = AVAudioSession.sharedInstance().availableInputs?.first { $0.portType == .builtInMic } {
                        
                        let micrphoneOrientation: AVAudioSession.Orientation = .front
                        
                        if let dataSources = builtInMicInput.dataSources {
                            for dataSource in dataSources where dataSource.orientation == micrphoneOrientation {
                                try? dataSource.setPreferredPolarPattern(.cardioid)
                                try? builtInMicInput.setPreferredDataSource(dataSource)
                                break
                            }
                        }
                        try? audioSession.setPreferredInput(builtInMicInput)
                    }
                    try audioSession.setActive(true)
                    
                } catch let error as NSError {
                    print("Fail: \(error.localizedDescription)")
                }
            }
        
            audioDevice.block()```

#### Expected Behavior

The input microphone should be the front one.

#### Actual Behavior

The input microphone is the bottom one.

#### Reproduces How Often

100%

#### Logs
[twillioLogs.txt](https://github.com/twilio/twilio-video-ios/files/7428140/twillioLogs.txt)

#### Video iOS SDK

TwilioVideo -> latest 

#### Xcode

13.0

#### iOS Version

14.6 and 15

#### iOS Device

iPhone XR


 @ceaglest Can you help me?

**Comment by resetnic** [comment]
@ceaglest Can you help me?

**Comment by SaurabhBajaj** [comment]
Any update on this would be appreciated

**Comment by resetnic** [comment]
I have added [sample test repo](https://github.com/resetnic/Twillio-Audio-Video-Test/tree/9c9949dffd1e488f62083add7c2f9d59cdf9abc7) Twilio video quick start with some audio modification([contains the above code](https://github.com/resetnic/Twillio-Audio-Video-Test/blob/9c9949dffd1e488f62083add7c2f9d59cdf9abc7/VideoQuickStart/ViewController.swift#L129)) and it behaves in the same way. The microphone selection issue is also present in the earlier versions of twilio.

**Comment by wolfspy** [comment]
Using the `DefaultAudioDevice` as in the VideoQuickStart app does not support different microphone orientations. Instead you must roll your own audio device as shown in the `AudioDeviceExample` app in order to provide the settings necessary to be able to change microphone orientations.

Specifically you’ll need to roll your own `AVAudioEngineDevice` that uses the `kAudioUnitSubType_RemoteIO` `componentSubType` of your `AudioComponentDescription`.
In the `ExampleAVAudioEngineDevice.m` file, update `audioUnitDescription.componentSubType = kAudioUnitSubType_VoiceProcessingIO;` to `audioUnitDescription.componentSubType = kAudioUnitSubType_RemoteIO;` 

The reason the VideoQuickStart app only allows the bottom mic is because the `DefaultAudioDevice` uses `kAudioUnitSubType_VoiceProcessingIO` which only supports the bottom mic (on an iPhone at least).

Because of the `kAudioUnitSubType_RemoteIO` setting, you will not get hardware echo cancellation. However you can try enabling software echo cancellation instead on your microphone audio track.
```
let options = AudioOptions() { (builder: AudioOptionsBuilder) in
    builder.isSoftwareAecEnabled = true
}
localAudioTrack = LocalAudioTrack(options: options, enabled: true, name: "Microphone")
