### ISSUE TITLE
Size of TwilioVideo.framework

### ISSUE THREAD

**Issue by MilanNosal** [twilio/twilio-video-ios#24]
After including Twilio Video pod in my app the size of the app ballooned to over 200MB. After inspecting I noticed that TwilioVideo.framework file is 160MB. Is this normal? Is there anything that can be done to reduce it?

**Comment by piyushtank** [comment]
@MilanNosal Thanks for reaching out. The Video SDK is built for armv7, arm64, x86 and x86_64 architectures with Bitcode slices for armv7 and arm64 devices. We recommend strip simulator architectures for running app on device, and before submitting the app to the app store. See [[this](https://www.twilio.com/docs/video/ios)] for more information on strip architectures. 

Bitcode slices takes a big portion out of ~160MB of Video SDK size. Because bitcode is enabled, it helps [app thinning](https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f) by Apple App Store. (in other words, when you download your app from Apple App Store, you should see reduced size.)

Let us know if you have more questions.
