### ISSUE TITLE
Freeze last "successful" video frame

### ISSUE THREAD

**Issue by aastlind** [twilio/twilio-video-ios#26]
This is not an issue, but I'm reaching out for some help. If this isn't the right place to ask for help you can close this issue.

My question:
Is it possible to fetch the last known successful video frame (both local and remote) and convert it to a CIImage to do some image processing? My goal is to have a greyed out frame when losing/disabling video instead of showing a black screen.
In my head it has to be broken down into multiple steps:
- Copy the current frame to memory (while saving the previous frame in memory too)
- If current frame is black, take the previous frame from the memory and convert it to a CIImage
- Do the image processing

Is this possible to do?

**Comment by ceaglest** [comment]
Hi @aastlind,

> Is it possible to fetch the last known successful video frame (both local and remote) and convert it to a CIImage to do some image processing?

Yes, you could add your own renderer and simply hold a strong reference to the `TVIVideoFrame` that we provide you. This is roughly how `TVIVideoView` works. It holds on to the last fame and when its CADisplayLink timer fires it draws any new frame to screen using {OpenGL ES, Metal}.

We don't have an example in place, but you could look at ExampleSnapshotRenderer in this work in progress [PR](https://github.com/twilio/video-quickstart-swift/pull/286).

I will have to double check the disabling video case, because I believe that in Group Rooms the Media Server ceases sending frames to subscribes after disabling, while Peer-to-Peer would sometimes continue to send black frames.

Regards,
Chris

**Comment by piyushtank** [comment]
Closing an old ticket. Feel free to reach out to us if you have any questions.
