### ISSUE TITLE
Detect loss of connection

### ISSUE THREAD

**Issue by julien-l** [twilio/twilio-video-ios#28]
### Description

How to detect disconnection from an empty room with the Twilio SDK upon a loss of Internet connection?

For when the room is not empty, I can monitor the number bytes/packets received returned by `getStatsWithBlock()`; when they stop increasing, I can assume a loss of connection. But I was unable to find any useful stats when the room is empty.

Certainly related to known issue "Participant disconnect event can take up to 120 seconds to occur. #99"

### Steps to Reproduce

1. Connect to an empty room
2. Disconnect the device from Wi-Fi
3. No room disconnection is detected

#### Versions

Twilio SDK 2.5.2
iOS version > 11

**Comment by piyushtank** [comment]
@julien-l With our current implementation, the Video SDK internally runs SIP signaling session timer of 120 seconds. If the network is lost completely, the SDK waits upto the session timer expiry for network connection establishment. This is a similar [issue](https://github.com/twilio/video-quickstart-swift/issues/99) it takes upto 120 seconds for remote participant to detect the disconnect.

We are planning to make changes in our signaling layer in later this quarter. We are planning to move away from the SIP and implement better signaling for mobile SDKs. With the new signaling implementation, the disconnect event will not take up to 120 seconds. With new implementation, the disconnected  event may get invoked within 30 seconds but please note that we are still discussing on how sooner the event should get fired because the tradeoff is heartbeat between the SDK and the infrastructure.
