### ISSUE TITLE
Capturing popover? 

### ISSUE THREAD

**Issue by dannycohn** [twilio/twilio-video-ios#3]
I'm capturing a view and attaching as a track to a room. When I display popovers, because they are a separate view, they are not captured. Is there an easy way to capture them as well?

**Comment by paynerc** [comment]
Hey @dannycohn,

Are the popovers subviews of the view that you are capturing or a totally separate view altogether? When capturing, it should be capturing the view hierarchy from the view downward.

Can you provide some more information about what view you are capturing and where the popovers are in relation?

Thanks,

Ryan

**Comment by dannycohn** [comment]
I am creating them using the standard popover APIs, which I believe create them as a separate window floating over the main window. This is why it's not captured. I'm wondering if there's some trick to capturing it.

```
let popover = UIStoryboard(name: "SomePopover", bundle: Bundle.main)
                    .instantiateViewController(withIdentifier: "SomePopover") as? SomePopover

popover.modalPresentationStyle = .popover
popover.popoverPresentationController?.backgroundColor = UIColor.white
popover.popoverPresentationController?.sourceView = chart
popover.popoverPresentationController?.sourceRect = CGRect(x: chart.bounds.origin.x, y: yValue, width: chart.bounds.width, height: chart.bounds.height)
popover.popoverPresentationController?.permittedArrowDirections = showArrow == true ? .up : UIPopoverArrowDirection(rawValue: 0)

popover.popoverPresentationController?.delegate = self
present(popover, animated: true, completion: nil)
```

**Comment by paynerc** [comment]
@dannycohn,

Thanks for the info. I am going to need to do some testing here to see how best to make this work. I will try to work on this later today and hopefully either have an answer for you, or a plan on what we would need to do to be able to capture the popovers as well.

Stay tuned!

Ryan

**Comment by dannycohn** [comment]
Hey Ryan,

Sorry to be annoying, but curious if there's any status update on this? Even if it's just "on the docket" but not tackled yet, anything would be helpful. If we need to start rebuilding all of our popovers, the sooner we know the better we can plan.

Thanks,

Danny

**Comment by paynerc** [comment]
Danny,

Sorry for the lack of communication on this. I have been focused on wrapping up our `2.0.0-beta3` release which is coming out today. Once we have that out, I will definitely get you an answer on how to proceed.

Thanks for your continued patience,

Ryan

p.s. You're not being annoying at all. Thank you for keeping me honest. 😄

**Comment by theandrewmack** [comment]
Hey Ryan,

I am working on the same development team that Danny was on. I am wondering if you have had any progress on this item. Please let me know.

Thanks,
Andrew

**Comment by KBoucherChi** [comment]
Hi @paynerc,

Hope you're well. I'm on the same dev team as Andrew, I was wondering if you have any updates on this issue?

Regards,
Ken

**Comment by paynerc** [comment]
@KBoucherChi, @theandrewmack, @dannycohn,

My apologies for letting this slip off of my radar. I will dig back into this issue tomorrow morning when I get in and hope to have a resolution for you very shortly.

Thank you,

Ryan

**Comment by paynerc** [comment]
Good morning,

Sorry for the late response on this. Doing some investigation, a popover window is not contained in the same view hierarchy as the view it is being sourced from, which is why when you it is not rendered in the capturer.

The immediate solution that I have found to make this work (and it may not be applicable to your use case) is by capturing your application's `keyWindow`. This will cause all views that are displayed in your application (including popovers) to be captured.

The issue here is if you are only attempting to capture a certain view in the view hierarchy. If this is the case, we will need to do a bit more investigation. We do have a [ScreenCaptureExample](https://github.com/twilio/video-quickstart-swift/tree/master/ScreenCapturerExample) in Swift. You could use this as a starting point and navigate the application's window's views to find the pop over and render it with the view you are capturing.

Let me know if capturing the application's `keyWindow` will work for you.

Ryan

**Comment by KBoucherChi** [comment]
Thanks for the update Ryan, much appreciated! 
We'll try the above and let you know how we get on with that.

Cheers,
Ken

**Comment by KBoucherChi** [comment]
Hey Ryan,

We managed to fix it modifying the example in the ScreenCaptureExample and capturing the entire window, it now properly shows the popovers as expected.

Thanks for your input with this, much appreciated!

Ken

**Comment by paynerc** [comment]
Awesome news. Please let us know if you have any other questions or issues.

Ryan
