### ISSUE TITLE
It's possible for user to connect to completed room

### ISSUE THREAD

**Issue by Tratar** [twilio/twilio-video-ios#51]
### Description

It's possible for iOS to connect to completed room.

### Steps to Reproduce

1. Create room
2. Complete it with rest api
3. Try connecting to completed room.

#### Expected Behavior

User is not connected with error.

#### Actual Behavior

User is connected.
`- (void)didConnectToRoom:(nonnull TVIRoom *)room;` is called

#### Reproduces How Often

100%. Easy to reproduce.

#### Logs

There are no logs from Twilio at all.

### Versions

All relevant version information for the issue.

#### Video iOS SDK

2.10.0

#### Xcode

10.2

#### iOS Version

iOS10, iOS12

#### iOS Device

iPhone 5, iPhone 6

**Comment by ceaglest** [comment]
Hi @Tratar,

Thanks for your feedback about Room completion behavior.

> Create room
Complete it with rest api
Try connecting to completed room.

How do you connect to the completed Room? If you're connecting with an access token that is scoped to the Room's uniqueName then connecting to the just completed Room actually causes a new Ad-Hoc Room with the same name to be created (assuming Ad-Hoc creation is allowed).

> User is not connected with error.

I tried this locally, and saw the same results as you did. If you're creating Rooms via REST exclusively would you be possible to disable Ad-Hoc creation in the console and try again?

If you need both REST and Ad-Hoc creation then would you prefer tokens to be scoped to single Room SID rather than uniqueName?

![Screen Shot 2019-07-08 at 10 00 00 AM](https://user-images.githubusercontent.com/1302577/60828670-dc39f500-a167-11e9-8824-1d4853b71437.png)

Best,
Chris

**Comment by Tratar** [comment]
Hi @ceaglest,

Thanks much, you are absolutely right. We didn't know about that ad-hoc room creating.

**Comment by ceaglest** [comment]
Hi @Tratar,

If you need Ad-Hoc Room creation for another reason then you can also create access tokens scoped to a Room SID of a Room created via REST. These scenarios are possible with Ad-Hoc Room creation enabled:

* Complete a Room, then connect with a token scoped by name. A new Ad-Hoc Room is created with the same name, but a new SID
* Complete a Room, then connect with a token scoped to the Room's SID. The connection attempt fails with a RoomNotFound error (53106)

Best,
Chris

**Comment by Tratar** [comment]
Hi @ceaglest 

Thanks much for clarifications. They are really usefull. We will refine on room creating and token generating logic a bit. 

Best regards,
Michael
