### ISSUE TITLE
Rotation/Orientation Bug when calling iOS -> JS

### ISSUE THREAD

**Issue by mcorner** [twilio/twilio-video-ios#65]
### Description

Full description is here:
https://github.com/twilio/twilio-video.js/issues/803

But basically if you rotate the iOS device the video rotates correctly on the JS side, but doesn't rotate back correctly if you rotate the iOS device back to portrait.

Reporting this here to see if there is a workaround on the iOS side?  Or something we are missing?

### Steps to Reproduce

This is easily reproduced on the quickstart objc and quickstart js.

**Comment by ceaglest** [comment]
Hi @mcorner,

I responded to the JS issue. As for an iOS workaround, our upcoming 3.1.0 release will give you the ability to remove rotation tags on the sender side. It might help fix the Chrome/JS rendering issue because the physical dimensions will be changing each time the device is rotated.

Best,
Chris

**Comment by mcorner** [comment]
Thanks for the response.

Yes, that might be one way.  But wouldn't it be ambiguous between the two landscape rotations and the two portraits?  But I look forward to seeing some sample code.

For now we are using a manual rotation button with a css transform (the JS page is internal so we can get away with it).  That Chrome issue doesn't seem to have much activity so the likelihood of a fix there seems low.

**Comment by piyushtank** [comment]
Closing an old ticket. Feel free to reopen this or open a new ticket.
