### ISSUE TITLE
Silently dropped iOS 10.0 target support in v3.0

### ISSUE THREAD

**Issue by zabolotiny** [twilio/twilio-video-ios#75]
Dear Twilio team, your documentation says that iOS10 is supported with v3.1 but actual min deployment target is 11 starting from 3.0 beta5. 
Are you doing to drop support of iOS10? 
Is is possible to have a build of 3.1 with support of iOS10?

**Comment by ceaglest** [comment]
Hi @sheff1422,

Thanks for the feedback, we are always looking for opportunities to improve our documentation. In this case I think the 3.0.0 changelog could be clearer about changes to iOS support.

> Are you doing to drop support of iOS10?

Yes, we dropped support for iOS 10 in [3.0.0-beta6](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-3x#300-beta6-september-30-2019). The platform overview docs have [a table](https://www.twilio.com/docs/video/ios#xcode-and-ios-version-support) that lists iOS version support. The 2.x SDK continues to support iOS 10.

> Is is possible to have a build of 3.1 with support of iOS10?

No, we are not planning on doing this since the code needed to support iOS 10 has been removed.

Best,
Chris

**Comment by ceaglest** [comment]
Hi @sheff1422,

> Dear Twilio team, your documentation says that iOS10 is supported with v3.1

As a follow on question, is there somewhere in the docs where we claimed that 3.1.0 supports iOS 10? If so, please let us know and we will update it.

Best,
Chris
