### ISSUE TITLE
Sound Output Become Mono During Video Call

### ISSUE THREAD

**Issue by jeffryadityatama** [twilio/twilio-video-ios#77]
### Description

Hi twilio team, I'm developing feature that needs to play a local audio file while also doing the video call. The audio file is in stereo format and it works as expected in the Android. But in iOS the sound of audio file become mono when the video call session is ongoing. 

I wonder if there is any configuration that I need to change?

**Comment by ceaglest** [comment]
Hey @jeffryadityatama,

Yes, I think there is. By default the AVAudioSession is configured for mono to match the requirements of the VoiceProcessingIO audio unit that Twilio Video uses to play and record audio.

Could you reconfigure the AVAudioSession to prefer stereo output? We have a guide about providing a handler block to reconfigure AVAudioSession when using TVIDefaultAudioDevice:

https://www.twilio.com/docs/video/ios-v3-configuring-audio-video-inputs-and-outputs#selecting-specific-audio-routes

Best,
Chris

**Comment by jeffryadityatama** [comment]
Hi @ceaglest thanks for your help, will let you know soon about the result.

**Comment by jeffryadityatama** [comment]
Hi @ceaglest, I've been trying to alter the `AVAudioSession` when connect to the room. But it still doesn't work. The sound is still played in mono with lowered volume, it's like it treated as lower priority by the iOS
```
AVAudioSession *session = [AVAudioSession sharedInstance];
[session setCategory:AVAudioSessionCategoryPlayAndRecord mode:AVAudioSessionModeDefault options:AVAudioSessionCategoryOptionMixWithOthers error:nil];
[session setPreferredOutputNumberOfChannels:2 error:nil];
[session setActive:YES error:nil];
```
But if,I use category `AVAudioSessionCategoryPlayback`. It back to stereo again, but then Twilio voice couldn't be heard, which is not we want.

To make it clear how our system design, it looks like this:
![Screen Shot 2020-02-18 at 09 52 20](https://user-images.githubusercontent.com/6150874/74700263-91bc4300-5235-11ea-8b3f-f2926aa169eb.png)

So we have two user, one using PC browser, and another one using iPhone. So when the twilio connection established and they're doing the talk, user2 can also hear tone simultaneously. The tone is actually stored in the user2 device and we play it by using `AVAudioPlayer` locally.

I also tried to use example provided in [AudioDeviceExample](https://github.com/twilio/video-quickstart-ios/tree/master/AudioDeviceExample), changed the `mixLoop.caf` file with our stereo file, and change some configuration such as `kPreferredNumberOfChannels = 2` and change the `activeFormat` to use `TVIAudioChannelsStereo`, but still it being heard as mono.

To give you an idea what sound we use, you can download one of the file [here](https://www.act-emdrcentrum.nl/emdr/download-bestanden/#) and hear it by using headphone/earphone

**Comment by umarniz** [comment]
Hey @ceaglest would you have any recommendations on how to overcome this issue?

If I set the category to be `AVAudioSessionCategoryMultiRoute` then the correct stereo sound is played. I am not entirely sure why this is the case as the output device,  channels and the sample rate are exactly the same between `AVAudioSessionCategoryPlayAndRecord` and `AVAudioSessionCategoryMultiRoute`.

We are considering using `AVAudioSessionCategoryMultiRoute` as a workaround for now but it is indeed a hack to use and the mode doesn't support bluetooth headphones and hence would be a major problem for most of our users as well.

Any regarding this would be greatly appreciated!

**Comment by piyushtank** [comment]
Thanks @umarniz and @jeffryadityatama. Apologies for the delay. 
I tried a stereo file in AVAudioEngine example, and I am able to reproduce the problem you are observing. We will investigate the issue further and get back to you.

**Comment by umarniz** [comment]
> Thanks @umarniz and @jeffryadityatama. Apologies for the delay.
I tried a stereo file in AVAudioEngine example, and I am able to reproduce the problem you are observing. We will investigate the issue further and get back to you.

Thanks a lot @piyushtank let us know if you need anything from our end :)

**Comment by umarniz** [comment]
Hey @piyushtank is there any update on this issue?

This has been a major blocker on our end and we would be really happy to help with this in any way we can!

**Comment by hameshiv** [comment]
Hi guys,
We have exactly the same issue - audio signal turning to mono during a call, but stereo when the call is disabled - using Twilio javascript SDK on iOS.
I'd be glad to join the discussion and help, if possible.

**Comment by piyushtank** [comment]
@umarniz @hameshiv  - At present our team is busy working in upgrading WebRTC-83, so we haven't got chance to take a look at this issue yet.

One experiment I wanted to try is - since AVAudioEngine real-time audio processing APIs are relatively new, we can remove VideoSDK from the equation and try just playing the audio content from a file using real-time AVAudioEngine in your audio device. Does it give the expected stereo audio ? Unfortunately my sprint is busy with new WebRTC-84 upgrade tickets, if you have time I suggest performing this experiments to make sure AVAudioEngine works as expected.

**Comment by umarniz** [comment]
Hey @piyushtank thanks for coming back to us.

I understand that your team is busy with the WebRTC upgrade and can understand that there are only so many things that can be picked by a team.

From our side, we would really appreciate any help you can provide with this issue or help provide timelines on as it has unexpectedly blocked a major feature in our product for the last ~5 months and is becoming a critical bottleneck for expanding our use of Twilio calls in our product.


If I understood your recommendation correctly, you wanted to make sure that we can eliminate `AVAudioEngine` as a potential cause and hence test that the native iOS AVAudioEngine can indeed play a stereo sound correctly.

I can confirm that `AVAudioEngine` does indeed play stereo sounds correctly and also plays them on Bluetooth headphones. 

We have an internal library we use that uses AVAudioEngine but for double confirmation I used this open-source repo which uses the raw AVAudioEngine APIs: https://github.com/standinga/PlayAudioFile

**Comment by piyushtank** [comment]
@umarniz Correct I wanted to make sure that we can eliminate AVAudioEngine as a potential cause and hence test that the native iOS AVAudioEngine can indeed play a stereo sound correctly.

AVAudioEngine plays an audio file correctly in non-manual mode. However, in order to mix real-time audio sample with file audio, it requires to operate on [manual rendering mode](https://developer.apple.com/documentation/avfoundation/avaudioengine/2881237-enablemanualrenderingmode). 

In our audio device example for playout, we set the manual rendering mode  [here](https://github.com/twilio/video-quickstart-ios/blob/master/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m#L272-L275) , pass remote participant's audio sample to audio engine [here](https://github.com/twilio/video-quickstart-ios/blob/master/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m#L297-L324), and play music from a file [here](https://github.com/twilio/video-quickstart-ios/blob/master/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m#L399).

I tried to search real-time audio example with manual rendering mode in https://github.com/standinga/PlayAudioFile, but I couldn't find it.

Let me know how it goes.

**Comment by umarniz** [comment]
Hey @piyushtank 

Thanks a lot for continuing to guide us, this already gives more insight :)

For the test you suggested, I ran the `AudioDeviceExample` on 2 devices both of which were using the AVAudioEngine and then tried playing a stereo sound and noticed the sound was playing in Mono.

This does seem to point an issue related to manual rendering mode but to clarify, in our current case in our app we are creating two separate AVAudioDevice instances (one passed to Twilio iOS SDK and the other handled natively) and then letting the OS automatically mix these 2 streams.

For the problem with the manual rendering mode, I can say I tried the following settings:

1) Set the `activeFormat` to be stereo instead of mono: https://github.com/twilio/video-quickstart-ios/blob/master/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m#L784

2) Set the `kPreferredNumberOfChannels` to be 2 instead of 1: https://github.com/twilio/video-quickstart-ios/blob/master/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m#L14

3) Set the `mode` of the AVAudioSession to be `AVAudioSessionModeDefault` instead of `AVAudioSessionModeVideoChat` as this is a bit undocumented publicly and I thought might internally be changing the channels to be mono: https://github.com/twilio/video-quickstart-ios/blob/master/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m#L823

But all the settings combined still kept the playback sound in the manual mixing mode to be mono as well.

Maybe you would have a suggestion of what else I can test from here?

Thanks!

**Comment by umarniz** [comment]
**Update:** This issue also exists in Twilio Android SDK: https://github.com/twilio/video-quickstart-android/issues/533

**Comment by umarniz** [comment]
**Update**: The Android issue is completely unrelated and was happening only on Android OS < Android O. I found the root cause: https://github.com/twilio/video-quickstart-android/issues/533#issuecomment-647399857

The issue for iOS still exists and seems to have no relation to the issue in Android.

**Comment by umarniz** [comment]
After a lot of investigation, I have found the problem.

The root cause comes from the fact that `VoiceProcessingIO` is inherently monophonic: https://stackoverflow.com/a/29280608/1748032

This causes both, the way we play the audio i.e `AVAudioPlayer` to play a sound + Twilio to handle the WebRTC call + the `AudioDeviceExample` to play sound in mono.

The only way I could see to fix the problem is to make a custom audio device and render everything in manual mode, exactly like the AVAudioExample, with the only exception of making the IO unit to be `kAudioUnitSubType_RemoteIO` instead of `kAudioUnitSubType_VoiceProcessingIO`.

So in the AudioDeviceExample to modify this line: https://github.com/twilio/video-quickstart-ios/blob/master/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m#L792

@piyushtank thanks a lot for writing the AudioDevice example which does inherently provide a solution and I am looking forward to your comment on this as you understand CoreAudio and the AVFoundation much better than I do :)

**Comment by mazedude** [comment]
Not sure if this is the right place to ask, but I'm having the same issue from the Javascript SDK.  Video conferencing and stereo audio playback need to happen side-by-side on a website URL that can be accessed via desktop/laptop OR by mobile browser. On iOS or Android all audio gets condensed to mono. I've been digging through all of the Javascript documentation, common issues on Github, etc. for a while, and this thread is the only one close to addressing the issue... but unfortunately the iOS-specific solutions don't seem to have a clear parallel in the Javascript version of things. Any insight or suggestions of things to try would be greatly appreciated, thanks!

**Comment by piyushtank** [comment]
@mazedude I am not familier on how WebKit is implemented. + @makarandp0  to help with JS SDK. 

@umarniz What you found could be the problem why you are not observing only the stereo with AVAudioEngine. Please note, with `kAudioUnitSubType_RemoteIO`, iOS doesn't use inbuilt echo cancellation. You should use  enable software AEC using [this APIs](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIAudioOptions.html#//api/name/softwareAecEnabled) when RemoteIO is used.

Also, I have requested an appointment with Apple engineers from audio team at WWDC. If I get chance to talk to apple engineers, I will discuss this case with them.

Let me know if you have any questions.

**Comment by umarniz** [comment]
@mazedude I don't think I can help there but I can say that having gone a bit deeper into the WebRTC implementation itself, I have a guess that this might depend on how the browsers implement audio management and WebRTC so the behaviour might differ per browser.

For future reference to this issue itself, I have a draft PR which shows the changes required for stereo sound to work in the AudioDevice example: https://github.com/umarniz/video-quickstart-ios/pull/1/files

Once again, thanks a lot for making the audio device demo @piyushtank, your demo helped immensely in this hunt and it would have been much harder to get the answer without the demo 🙇

**Comment by winstondu** [comment]
@umarniz , unfortunately, your draft PR is almost a non-starter for anyone using Twilio's voice call SDKs. As someone on this thread already mentioned, when you use the RemoteIO audio unit, you give up on the echo cancellation capabilities.

**Comment by winstondu** [comment]
@piyushtank , sorry to occupy your time all day with my questions, but I also ran into this problem as well.

I suspect @umarniz's conclusion was correct: VPIO is monophonic. And because, from a technical standpoint, it is an audio unit that must be aware of all speaker sounds (in order to correctly cancel them out when they are picked up by the phone's mic again), all output audio (such as the file being played) must go though it.

I wonder if you have pinged Apple's engineers on when they might get stereo support for VPIO, as that would be much needed.

In any case, to reference my other thread, seems like this is another reason for our team to try to go with the Twilio software AES (I hope your AES algorithm is good!)

**Comment by umarniz** [comment]
@piyushtank Is this something that you discussed with Apple engineers?

I notice with iOS 14 my example repo that I shared doesn't work anymore :(

https://github.com/umarniz/video-quickstart-ios/pull/1

**Comment by piyushtank** [comment]
@umarniz @winstondu 
We learned that VoiceProcesing AudioUnit (VPIO) doesn't support true stereo. So if the stereo file is being played by VPIO AudioUnit, it wont be able to play the stereo. Unfortunately, we did not receive any timeline when VPIO will support stereo. If you want to use RemoteIO and you should use software echo cancellation by setting [AudioOptions.softwareAEC](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIAudioOptions.html#//api/name/softwareAecEnabled) property.

**Comment by umarniz** [comment]
@piyushtank thanks for the response.

I see now that as of iOS 14 the `AVAudioSessionModeVideoChat` and `AVAudioSessionModeVoiceChat` are made to be completely mono.

This was not the case on iOS < 14.

I am not sure if you informing about you discussing the mono nature of the VPIO had something to do with it but the timing is certainly interesting ;)

The solution is to enforce the mode to be `AVAudioSessionModeDefault` but only for iOS 14.

Strangely enough `AVAudioSessionModeDefault` causes the audio to be mono on iOS 13 :(

Its annoying to see the behaviour of voice and video modes change between different iOS version without any apparent differences on the lower level (i.e audio units are all still stereo).

Eitherways, thanks again for the help!

I have updated my PR to reflect the changes to make stereo work on iOS 14+ and < iOS 14: https://github.com/umarniz/video-quickstart-ios/pull/1

**Comment by piyushtank** [comment]
@umarniz Thanks for sharing your findings on `AVAudioSessionModeDefault` and the branch.
