### ISSUE TITLE
No audio when answer from background

### ISSUE THREAD

**Issue by carayolthomas** [twilio/twilio-video-ios#8]
Hello there,

### Description

I am currently working on a POC for a chat application between two users. We are creating twilio rooms in our backend and then, we communicate through our API the room id and the access token needed to connect both users in the created room. It works pretty well (audio & video) when both applications are active.
On the called side, I am trying to answer a call with CallKit when my app is killed and my device is locked.

The app seems to works well if you look at the logs below 

```
2018/04/20 16:45:43:696  didAnswer
2018/04/20 16:45:44:031  Connecting to room : Optional(<TVILocalAudioTrack: 0x1c0249f00>) - Optional(<TVILocalVideoTrack: 0x1c0467100>)
2018/04/20 16:45:44:963  Connected to room : Optional(<TVILocalAudioTrack: 0x1c0249f00>) - Optional(<TVILocalVideoTrack: 0x1c0467100>)
2018/04/20 16:45:44:970  Speaker error : Error Domain=NSOSStatusErrorDomain Code=1701737535 "(null)"
```

The called user is connected to the room, however, **I've got no audio**. Even if, the audio local track seems to be instantiated. 
As you can see in the last line of the logs, I've got an error when I am trying to execute the following code 

```
do {
            try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, mode: AVAudioSessionModeVoiceChat, options: .mixWithOthers)
            try AVAudioSession.sharedInstance().overrideOutputAudioPort(.speaker)
            try AVAudioSession.sharedInstance().setActive(true)
        } catch {
            DDLogInfo("Speaker error : \(error)")
        }
```

I have set "audio" and "voip" as background modes of my app.
I am a stuck there. I don't really know where to look for some hints about this error.

Have you experienced errors like this? 
Do you have any advices about where this problem might come from?

Thanks a lot.

#### Video iOS SDK

1.4.0 via CocoaPods

#### Xcode

9.3

#### iOS Version

iOS 11.1.2

#### iOS Device

iPhone 6

**Comment by carayolthomas** [comment]
I found a potential fix for my issue. It's not about Twilio but CallKit.

We need to setup the `AudioSession` before reporting a new incoming call from CallKit.

Something like this 

```
do {
                try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, mode: AVAudioSessionModeVoiceChat, options: .mixWithOthers)
                try AVAudioSession.sharedInstance().overrideOutputAudioPort(.speaker)
                try AVAudioSession.sharedInstance().setActive(true)
            } catch {
                DDLogInfo("Speaker error : \(error)")
            }
            
            strongSelf.provider.reportNewIncomingCall(with: strongSelf.uuid, update: strongSelf.update, completion: { error in })
```

You can close this issue :)

Have a good day!

**Comment by paynerc** [comment]
@carayolthomas,

You beat me to it. I was writing up a response to ask you where and when you were running these methods.

Glad you got it resolved!

Ryan

**Comment by Worien** [comment]
> I found a potential fix for my issue. It's not about Twilio but CallKit.
> 
> We need to setup the `AudioSession` before reporting a new incoming call from CallKit.
> 
> Something like this
> 
> ```
> do {
>                 try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, mode: AVAudioSessionModeVoiceChat, options: .mixWithOthers)
>                 try AVAudioSession.sharedInstance().overrideOutputAudioPort(.speaker)
>                 try AVAudioSession.sharedInstance().setActive(true)
>             } catch {
>                 DDLogInfo("Speaker error : \(error)")
>             }
>             
>             strongSelf.provider.reportNewIncomingCall(with: strongSelf.uuid, update: strongSelf.update, completion: { error in })
> ```
> 
> You can close this issue :)
> 
> 
You are the hero of my day

**Comment by piyushtank** [comment]
@Worien For Video calls, ideally we should be using the VideoChat mode which will route the audio to speaker. I would modify the workaround to following.

```
          do {
                try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, mode: AVAudioSessionModeVideoChat, options: .mixWithOthers)
                try AVAudioSession.sharedInstance().setActive(true)
            } catch {
                DDLogInfo("Speaker error : \(error)")
            }
            
            strongSelf.provider.reportNewIncomingCall(with: strongSelf.uuid, update: strongSelf.update, completion: { error in })
```

Let me know if you run into issue with ^ workaround.

**Comment by Worien** [comment]
It seems this solution doesn't fix the bug when you accept the call in callkit in locked-screen mode. You still don't have a sound.

**Comment by jvanakker** [comment]
Same problem here. wilio 3.x SDK. In our case, an outgoing call that's programmatically initiated. We don't use Callkit. And in our case it's TwilioVoice.

The function "toggleAudioRoute:(BOOL)toSpeaker" (provided in the ObjCVoiceQuickstart sample code) with "toSpeaker" set to YES, does work with the app in foreground, but does NOT work in background (phone locked or just app in background). The call is connected, but no audio can be heard on either side of the call. Any thoughts?

**Comment by piyushtank** [comment]
@jvanakker Thanks for reaching out. Let me make sure if I understood the used case completely. If your app is not using the CallKit, how are you toggling the audio when app is backgrounded?

**Comment by jvanakker** [comment]
@piyushtank Twilio provides two example implementations for integrating TwilioVoice: one using CallKit and one without. The integration in our application is based on the one that's **not** using CallKit (as we have our own calling UI integration and don't want to use the Apple calling UI, etc).

Our outgoing call is initiated programatically and forced through the speaker and has been working perfectly. However, we have now noticed that the audio does not work when the call is initiated while backgrounded. It also doesn't work when **not** forcing through speaker, so that doesn't matter. The call itself is actually there, it's just the audio thats absent. However, when the call is initiated with the app in foreground, and when you _then_ switch to background, the audio keeps working fine.

**Comment by jvanakker** [comment]
More info: If I enable Twilio debug info, I can see this error in the log, which is probably related to the no-audio problem when the app is backgrounded:
AUIOClient_StartIO failed (561145187)

Some solutions to this general error, suggest enabling AVAudioSessionCategoryPlayAndRecord for the AudioSession. It does however not solve the problem in this case.

**Looking elsewhere, I found that this seems to be occurring since iOS 12.4 and iOS 13. I have just verified, the problem does NOT occur on iOS 11.x, but it does on 12.4!**
On 11.x our app works fine on with the outgoing call and correct audio while the app is backgrounded. I haven't found a solution yet for this problem on iOS 12.4 (and potentially iOS 13).

**Comment by varun-gadre** [comment]
Did anyone manage to solve this?

**Comment by piyushtank** [comment]
This problem hasn't been fixed yet - https://github.com/twilio/voice-quickstart-ios/issues/299

**Comment by madhu-kadyala** [comment]
We are also facing the same audio and mic issue when the device was in lock and call answered from callKit audio & mic is working then tap on video/app button from call kit UI, after redirecting to app audio & mic both are not working in twilio video call.

If anyone has a solution please help us to solve this issue.

func configureAudioSession() {
        print("Configuring audio session")
        let session = AVAudioSession.sharedInstance()
        do {
            try session.setCategory(AVAudioSessionCategoryPlayAndRecord, mode: AVAudioSessionModeVoiceChat, options: [])
         
        } catch (let error) {
            print("Error while configuring audio session: \(error)")
           
        }
    }

**Comment by odieatla** [comment]
Has anyone verified this on iOS 14? I'm still having trouble to have audio through when app is in the background. The error message I received is "-CMSUtilities- CMSUtility_IsAllowedToStartRecording: Client sid:0x25aec, <private>(2525), 'prim' with PID 2525 is in the background and doesn't have the entitlement to start recording in the background." I'm not using CallKit.

**Comment by abdullahumer** [comment]
I am facing this same issue. Anyone have a solution? Please help. Is this issue closed without a fix?

**Comment by hungMta** [comment]
I faced this issue and I tried to investigate the problem. Finally, I fixed in my case but hope it helps.
**Problem**: Can't receive audio when the app is locked
**Reason**: I waited for all the connections, room and many thing setup completed before trigger call answerAction.fullfill()
**CallKit**: when answer action is fulfilled then the AudioSession changes to didActive status => you can hear the voice in the background
But I fulfill the answer action after the audio of Twilio (WebRTC) is created => I can't hear the voice
**Debug**:  _didSubscribeToAudioTrack_ is triggered before  _provider(_ provider: CXProvider, didActivate audioSession: AVAudioSession)_
**Solution**: try to fulfill the answer action before  _didSubscribeToAudioTrack_ is triggered. Maybe you can hear the voice after 0 -> 1s when the timer on the calling screen is started but I think it's acceptable.
I call answerAction.fulfill() on  _roomDidConnect(room: Room)_ function
```swift
    func roomDidConnect(room: Room) {
        p("roomDidConnect", room)
        p("TwilioObj#didConnect", room)
        /// ..... do other things ......
        callkit_answer_action.fulfill() // this will active audio session
    }
```
