### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by manisha-PBH** [twilio/twilio-video-ios#85]
Uable to receive the audio when video call gets connect. In our app we are using audio call first and when user gets connect through VOIP we disconnect the audio call and then the video call. Most of the time audio does not comes up.

**Comment by piyushtank** [comment]
@ManishaAstaPartners In order to debug the problem can you provide following information?

- How was the first first audio call established? was it a PSTN call or an audio call using our SDK? Are you using CallKit in your app?

- Can you fill the git hub issue template? 


> Before filing an issue please check that the issue is not already addressed by the following:
>
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x)
> 
> If this is an issue with the SDK itself, file it here. If this is an issue with the QuickStart apps, please use [video-quickstart-ios](https://github.com/twilio/video-quickstart-ios/issues).
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Logs
Debug level logs are helpful when investigating issues. To enable debug level logging, add the following code to your application:

```.swift
TwilioVideoSDK.setLogLevel(.debug)
```

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

[e.g. 1.3.12 via CocoaPods]

#### Xcode

[e.g. 9.2]

#### iOS Version

[e.g. 11.2.6]

#### iOS Device

[e.g. iPhone 8 Plus]

**Comment by manisha-PBH** [comment]
Hi Piyush, Thanks for your reply
We have used twilio voice kit to start the call and then call kit yes but
since we wanna add video call to so what we have done is initiated the
voice call and as soon as the call gets connect we disconnet the audio call
and join the video call. So sometimes we do not get the audio. If possible
let me know your availability we can discuss it over call too.

**Comment by piyushtank** [comment]
@ManishaAstaPartners Can you send call sid from the VoIP Call?

Also I noticed you have opened ticket on `video-quickstart-ios` repo https://github.com/twilio/video-quickstart-ios/issues/469. Let use this ticket to address the issue you are running into. I will close the other but feel free to reopen if think otherwise.

**Comment by ManishaAstaPartners** [comment]
Sure , you can close that ticket.
SID for my voice call project is
AC8fe0fca576fa1d39102e7e28e16d1937It would be great if we can connect over
a call and you can help me out.

**Comment by piyushtank** [comment]
What you provided is account sid. Can you provide CallSid? You can get it by `call.sid` of a VoIP call.

**Comment by manisha-PBH** [comment]
Hi @piyushtank , 
Hope you are doing well. Sorry for the delay. 
The call SID  is :- CAca8762d439b36d8f05156c73b2276bac

**Comment by manisha-PBH** [comment]
https://drive.google.com/file/d/1ukJdx4vTPgbrLjVqdGWs3bsLljUCGtaJ/view?usp=sharing

The Demo that includes the issue i am talking about : 
You need to provide value in CallController.swift L.no: 37
You need to provide value in VideoConferenceVC.swift L.no: 87

On foreground it works correctly and if the app is in background the issue with audio started

**Comment by piyushtank** [comment]
@ManishaAstaPartners Thanks. I don't have permissions to the project just shared via google drive. I have requested for the permissions, my email is ptank@twilio.com

**Comment by manisha-PBH** [comment]
Hi Piyush,

Please check now. Sorry my mistake.

**Comment by piyushtank** [comment]
Thanks. I haven't ran the app locally but at a first glance, you should make following changes - 

In ViewController.swift viewDidLoad or init you should - 
```objc
override func viewDidLoad () {
    TwilioVideo.audioDevice = DefaultAudioDevice()
    self.audioDevice = TwilioVideo.audioDevice
}
```

```objc
func provider(_ provider: CXProvider, perform action: CXAnswerCallAction) {
    // reject invite here, as you no need to connect the voice sdk (voip) call
}
```

for voip calls, I would provide `answerOnBridge` as param, which will make the call end-to-end. 

You app will require changes at other places to accommodate above improvements. 

Let me know if this helps.

**Comment by manisha-PBH** [comment]
Sure, will do that.

But can you please guide me on how to integrate Video call with Voip .

For running the app you will need to change the base url on our controller
file.

If you will see the video view controller what we have done is as soon as
user gets connect to the room we are disconnecting the voice call. And i
think that is something we are doing wrong.
 Let me know your thoughts.
Thanks

**Comment by piyushtank** [comment]
@ManishaAstaPartners Did the above suggestion fix the problem for you?

**Comment by manisha-PBH** [comment]
No, it doesn't work.

**Comment by piyushtank** [comment]
I looked into the app you shared - I have made some changes to have the basic incoming call functions working - audio worked when the app is foregrounded and in background. Also, I noticed the app had lot of commented code and few issues in UI and flow, I will leave them up to you to fix.

Let me know your email address, I will share the changes with you.

**Comment by piyushtank** [comment]
^ cc @ManishaAstaPartners

**Comment by piyushtank** [comment]
Closing the ticket assuming you were able to resolve the issue, but feel free to reopen this or reach out via another ticket if you run into any issues. Thanks.

**Comment by Balasnest** [comment]
@ManishaAstaPartners Can you share those changes with us. I would like to check the fixes as it help us also.

**Comment by Naiyer95** [comment]
Hi @piyushtank I am getting same issue on Video call, Let me tell you what happened my end when make build and call at first time then voice is getting but when try again to call then I am not getting voice.
may I know why this happened what I am doing wrong.

**Comment by pawanmakkar67** [comment]
> I looked into the app you shared - I have made some changes to have the basic incoming call functions working - audio worked when the app is foregrounded and in background. Also, I noticed the app had lot of commented code and few issues in UI and flow, I will leave them up to you to fix.
> 
> Let me know your email address, I will share the changes with you.

pawanmakkar67@gmail.com
