### ISSUE TITLE
`UI API called from background thread Group` has occurred in Twilio Video 2.0.0

### ISSUE THREAD

**Issue by kboy-silvergym** [twilio/twilio-video-ios#9]
Hi! Thank you for your SDK!

I use your SDK in my iOS app that using ARKit in Japan.

When I use Twilio Video 2.0.0, The following alert has occurred! 
Please check.

### Description

When `participantDidDisconnect` , The alert (`UI API called from background thread Group`) has occurred.

### Steps to Reproduce

1. connect to twilio room

```swift
room = TwilioVideo.connect(with: options, delegate: self)
```

2. disconnected by partner exited 

```swift
func room(_ room: TVIRoom, participantDidDisconnect participant: TVIRemoteParticipant) {
    delegate?.participantDidDisconnect(participant.identity)
}
```

3. Then, alert about Main Thread has occurred.

#### Expected Behavior

UI API should be called from background thread

#### Actual Behavior

These alert.

>runtime: UI API called from background thread: -[UIView setTransform:] must be used from main thread only

>runtime: UI API called from background thread: -[UIView setNeedsLayout] must be used from main thread only

#### Logs

<img width="308" alt="2018-04-29 20 50 14" src="https://user-images.githubusercontent.com/17683316/39406260-f9f0f730-4bee-11e8-8f37-6142567de860.png">

#### Video iOS SDK

2.0.0 via CocoaPods

#### Xcode

9.3

#### iOS Version

11.3

#### iOS Device

iPhone 8, iPhoneX

**Comment by piyushtank** [comment]
@kboy-silvergym Thanks for reaching out. Can you answer following  - 

1. Can you make sure the is not calling `[TVIRemoteVideoTrack removeRenderer:]` or `[TVILocalVideoTrack removeRenderer:]` on a background thread?

2. How are you destroying the remote video track? Are you explicitly destroying them on the background thread?

3. Is it possible to provide the logs to debug this problem. You can enable the logs by following - 
```
        TwilioVideo.setLogLevel(.debug, module: .platform)
        TwilioVideo.setLogLevel(.debug, module: .core)
```

4. How reproducible the problem is - are you able to reproduce this problem on 2.0.0 again ? To make sure this is not a regression in 2.0.0 release, are you able to reproduce the problem in `2.0.0-beta4` ?

I am sorry for the inconvenience caused by this issue. We would like to fix this problem as soon as possible and we greatly appreciate your help.

**Comment by kboy-silvergym** [comment]
@piyushtank 

Thank you for your reply👍
I'll answer only No.4 anyway.

>How reproducible the problem is - are you able to reproduce this problem on 2.0.0 again ? To make sure this is not a regression in 2.0.0 release, are you able to reproduce the problem in 2.0.0-beta4 ?

I have used TwilioVideo SDK since `2.0.0-beta2`, but it was the first time to be occured in `2.0.0`. 
It always reproduces in `2.0.0`.

I will let you know when I have more information about question 1, 2, 3.

**Comment by ceaglest** [comment]
Hey @kboy-silvergym,

We found that in 2.0.0 there were some cases where invalidating a TVIVideoView (which is itself a TVIVideoRenderer) could cause UIKit accesses on a background thread. This could occur when removing a TVIVideoView from a TVIVideoTrack off the main thread, or providing your own delegateQueue to TVIConnectOptions, and causing the Track to be invalidated with renderers still present.

In our [2.0.1](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#201-may-4-2018) release we ensure that invalidating a TVIVideoView is always serialized to the main thread. Please give it a look when you have some time.

Best,
Chris

**Comment by kboy-silvergym** [comment]
@ceaglest 

I have ensured that the alert was not occured in ver. 2.0.1.
Thank you for support!! 👍

**Comment by piyushtank** [comment]
Thanks @kboy-silvergym for closing the ticket. Let us know if you run into any issues while using the video SDK.
