### ISSUE TITLE
Simulcast with iPad Pro uses very low frame size

### ISSUE THREAD

**Issue by sleman** [twilio/twilio-video-ios#96]
### Description

Use ipad 11" Pro MTXN2LL/A and simulcast returns a 640x360 frame size video sent to receivers.

### Steps to Reproduce

Use latest ios sdk.

Set codec to: vp8 simulcast
Set videoFormat to one with 1280x72
Set format framerate to 24.

#### Expected Behavior

1280x720 is captured as iPad can easily handle encoding as it's the latest model on par with iPhone.
#### Actual Behavior

Very low frame size of 640x360 is captured and sent to receivers.

#### Reproduces How Often

100%

```
// Log output when the issue occurs
```

#### Video iOS SDK

3.2

#### Xcode

11.4

#### iOS Version

[e.g. 11.2.6]

#### iOS Device

Apple 11-Inch iPad Pro

**Comment by piyushtank** [comment]
@sleman Simulcast is more dependent on the receiver side vs the sender side. The capturer encodes and sends three spatial layers, and depending on the remote participant's (network) conditions, out of three layers, our SFU forwards one layer to the receiver. [Here](https://www.twilio.com/docs/video/tutorials/working-with-vp8-simulcast) is the documentation on how simulcast feature is implemented. 

iPad could send frames with lower frame resolution due to the network condition, one way to check the frame size iPad is capturing and encoded before sending is using the [stats apis](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIRoom.html#//api/name/getStatsWithBlock:). 

Let me know if you have any questions.
